quitOnTopLevelReturn: true
showOutput: true
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
services:
  'git.u-next.com': 'gitlab:git.u-next.com'
customCommands:
  - key: 'g'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'Which branch do you want to Create PR to ?'
        key: 'TargetBranch'
        options:
          - name: 'develop'
            description: 'The Develop Environment Branch'
            value: 'develop'
          - name: 'qa'
            description: 'The QA Environment Branch'
            value: 'qa'
          - name: 'master'
            description: 'The Master Environment Branch'
            value: 'master'
      - type: 'input'
        title: 'Input your PR title'
        key: 'PullRequestTitle'
        initialValue: ''
    command: '{{ $url := (index .SelectedRemote.Urls 0) }} {{ $target_branch_prefix := "[Master]" }} {{ if eq .Form.TargetBranch "qa" }} {{ $target_branch_prefix = "[QA]" }} {{ else if eq .Form.TargetBranch "develop" }} {{ $target_branch_prefix = "" }} {{ end }} open "{{ $url }}/-/merge_requests/new?merge_request[source_branch]={{ .SelectedLocalBranch.Name }}&merge_request[target_branch]={{ .Form.TargetBranch }}&merge_request[title]={{ $target_branch_prefix }}{{ .Form.PullRequestTitle }}"'
    loadingText: 'Opening Pull Request'
  - key: 'f'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What is the name of your base branch'
        key: 'BranchType'
        options:
          - name: 'master'
            description: 'The master branch'
            value: 'master'
          - name: 'qa'
            description: 'The QA branch'
            value: 'qa'
          - name: 'develop'
            description: 'The develop branch'
            value: 'develop'
      - type: 'input'
        title: 'What is the new branch name?'
        key: 'BranchName'
        initialValue: ''
    command: "git checkout {{ .Form.BranchType }}"
    command: "git pull origin {{ .Form.BranchType }}"
    command: "git checkout -b {{ .Form.BranchName }}"
    loadingText: 'Creating feature branch'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
theme:
  activeBorderColor:
    - '#c6a0f6'
    - bold
  inactiveBorderColor:
    - '#a5adcb'
  optionsTextColor:
    - '#8aadf4'
  selectedLineBgColor:
    - '#363a4f'
  selectedRangeBgColor:
    - '#363a4f'
  cherryPickedCommitBgColor:
    - '#494d64'
  cherryPickedCommitFgColor:
    - '#c6a0f6'
  unstagedChangesColor:
    - '#ed8796'
  defaultFgColor:
    - '#cad3f5'
  searchingActiveBorderColor:
    - '#eed49f'
